project_name/apps/pages/urls.py
from django.conf.urls import patterns, include, url
from .views import AboutView, TermsView, DisclaimerView, contact

urlpatterns = patterns('',
   url(r'^about/$', AboutView.as_view(), name='pages_about'),
   url(r'^terms/$', TermsView.as_view(), name='pages_terms'),
   url(r'^disclaimer/$', DisclaimerView.as_view(), name='pages_disclaimer'),
   url(r'^contact/$',contact, name='pages_contact'),
)

project_name/project_name/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings

urlpatterns = patterns('',
    url(r'', include('apps.pages.urls')),
)

urlpatterns += staticfiles_urlpatterns()

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns += patterns('',
        url(r'^rosetta/', include('rosetta.urls')),
    )

project_name/apps/pages/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import TemplateView

from django import forms

class ContactForm(forms.Form):
    city = forms.CharField(max_length=100, required=True)
    name = forms.CharField(max_length=100, required=True)
    sender = forms.EmailField(required=True)
    telephone = forms.CharField(max_length=100, required=False)
    comment = forms.CharField(widget=forms.Textarea, required=False)
    cc_myself = forms.BooleanField(required=False)
    
class AboutView(TemplateView):
    template_name = "pages/about.html"
    
def contact(request):
    context = {}
    if request.method == 'POST': # If the form has been submitted...
        # ContactForm was defined in the the previous section
        form = ContactForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            # Process the data in form.cleaned_data
            city = form.cleaned_data['city']
            name = form.cleaned_data['name']
            comment = form.cleaned_data['comment']
            telephone = form.cleaned_data['telephone']
            sender = form.cleaned_data['sender']
            cc_myself = form.cleaned_data['cc_myself']
            recipients = ['info@pixelactions.com']
            if cc_myself:
                recipients.append(sender)

            subject = name + ' from ' + city
            comment = "[TEL:" + telephone + "]\n" + comment
            
            from django.core.mail import send_mail
            send_mail(subject, comment, sender, recipients)
            
            context['formsuccess'] = True
            form = ContactForm() # An unbound form
            #return HttpResponseRedirect('/thanks/') # Redirect after POST
    else:
        form = ContactForm() # An unbound form
    context['form']= form
    
    return render(request, 'pages/contact.html', context)

class TermsView(TemplateView):
    template_name = "pages/terms.html"
class DisclaimerView(TemplateView):
    template_name = "pages/disclaimer.html"

project_name/templates/base.html
<!DOCTYPE html>
    <head>
        {% block head %}
        {% endblock %}
    </head>
    <body>
        {% block content %}
        {% endblock %}
    </body>
</html>

project_name/templates/pages/about.html
{% extends "base.html" %}

project_name/templates/pages/contact.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}

    <h1>{% trans "Quick Contact" %}</h1>
   
   {% if formsuccess %}
   <h2>{% trans "Thank you for your message!" %}</h2>
   {% else %}
   <!-- Form generated from crispt forms -->
   <form action="{% url 'pages_contact' %}" method="post">
        {{form|crispy}}
        <input class="btn btn-primary" type="submit" value="Submit">
   </form>
   
   <!-- Form specified explicitly -->
    <form action="{% url 'pages_contact' %}" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="fieldWrapper">
            <label for="id_city">{% trans "City" %}: <span class="required">*</span><span>{{ form.city.errors }}</span></label>
            {{ form.city }}
        </div>
        <div class="fieldWrapper">
            
            <label for="id_name">{% trans "Name" %}: <span class="required">*</span> <span>{{ form.name.errors }}</span></label>
            {{ form.name }}
        </div>
        <div class="fieldWrapper">
            
            <label for="id_sender">{% trans "Email Adress" %}: <span class="required">*</span> <span>{{ form.sender.errors }}</span></label>
            {{ form.sender }}
        </div>
        <div class="fieldWrapper">
            
            <label for="id_telephone">{% trans "Telephone" %} <span>{{ form.telephone.errors }}</span></label>
            {{ form.telephone }}
        </div>
        <div class="fieldWrapper">
            <label for="id_comment">{% trans "Comment" %} <span>{{ form.comment.errors }}</span></label>
            {{ form.comment }}
        </div>
        <div class="fieldWrapper">
            <label for="id_cc_myself">{% trans "Send a copy to my email" %} <span>{{ form.cc_myself.errors }}</span></label>
            {{ form.cc_myself }}
        </div>
        <div class="required-field pull-right">* {% trans "Required Field" %}</div>
        <div class="clearfix"></div>
        <input class="btn btn-primary" type="submit" value="Submit">
    </form>
   {% endif %}
{% endblock %}

project_name/templates/pages/disclaimer.html
{% extends "base.html" %}

project_name/templates/pages/terms.html
{% extends "base.html" %}